---

- src: https://github.com/colin-mccarthy/Ansible_Cisco_ios_12.2_hardening_role.git
  name: Ansible_Cisco_ios_12.2_hardening_role
  scm: git
  version: master
  
- src: https://github.com/colin-mccarthy/Ansible_Cisco_ios_12.2_hardening_w-template.git
  name: Ansible_Cisco_ios_12.2_hardening_w-template
  scm: git
  version: master
  
  
 
