---
- hosts: sandbox-iosxe-latest-1.cisco.com
  gather_facts: false
  tasks :
    - name: Getting the definition of awesome
      uri:
        url: https://api.chucknorris.io/jokes/random
        method: GET
      register: results

    - debug:
            var: results