---
  -
    hosts : sandbox-iosxe-latest-1.cisco.com
    gather_facts : false
    tasks :
      - name : configure hostname 
        ios_config :
          lines : 
            - "hostname {{ inventory_hostname }}"

      - name : do a config back up 
        ios_config :
          backup : yes
          #provider : "{{ cli }}"

      # - name : write configuration and save it 
      #   ios_config :
      #     src : "{{ src }}"
      #     save : yes
      #    # provider : "{{ cli }}"
      #   register : cmd_output

      # - debug : var=cmd_output

      
...