---
  -
    hosts : sandbox-iosxe-latest-1.cisco.com
    gather_facts : false
    connection : local

    
    tasks :

      - name : change login banner 
        ios_banner :
          banner : login
          text : THIS BANNER IS FROM MICROSOFT
          state : present
      
      
      - name : change login banner - SECOND UPDATE  
        ios_banner :
          banner : login
          text : "{{ lookup('file', './mybanner.cfg') }}"
          state : present


      - name : delete banner 
        ios_banner :
          banner : motd
          state : absent

...