---
  -
    hosts : iosxe
    gather_facts : false
    connection : local

    tasks :
      - name : Test Host vars
        debug : 
          msg : "{{ inventory_hostname }} "

      - name : Test Host name 
        debug : 
          msg : "{{ hostvars[ansible_host] }} "


      - name : Test Host vars
        debug : 
          msg : "{{ hostvars[ansible_host].ansible_user }} "

      - name : Test Host vars dict notation 
        debug : 
          msg : "{{ hostvars[ansible_host]['ansible_version'] }} "
...


